[project]
name = "openai-assistants-python-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.3",
    "jinja2>=3.1.4",
    "openai>=1.52.2",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.32.0",
]
